before_script:
  - echo "start job at :" `date`
  - echo "workspace is:" `pwd`

after_script:
  - echo "done job at :" `date`

image: golang:1.20

stages:
  - test 
  - build
  - deploy

testApp:
  stage: test
  script:
   - echo "testing....." :rocket

buildApp:
  stage: build
  script:
   - echo "building....."
   - go mod tidy
   - go build ./...

deployApp:
  stage: deploy
  script:
   - echo "deploying....." :airplane